title: 
  fr: "Notre expertise"

subtitle: 
  fr: "Donner aux organisations de santé les moyens de transformer la complexité administrative en excellence opérationnelle grâce à la technologie open source."

items:
  fr:
    - icon: "/assets/images/undraw_programming.svg"
      title: "Développement d’applications"
      description: "Applications web sur mesure adaptées à l’administration des soins de santé, de plateformes intuitives pour la gestion des contestations d'assurances à de l’automatisation administrative en tenant compte des contraintes de vos systèmes existants."
    
    - icon: "/assets/images/undraw_presentation.svg"
      title: "Optimisation des processus & conseil"
      description: "Analyse experte et accompagnement stratégique pour rationaliser vos opérations administratives. Nous identifions les points de friction, concevons des flux de travail efficaces et mettons en œuvre des solutions d’automatisation qui réduisent le travail manuel et améliorent la précision."
    
    - icon: "/assets/images/undraw_diary.svg"
      title: "Collecte et intégration des données"
      description: "Formulaires web avancés et outils de collecte de données permettant d’injecter directement les informations dans vos systèmes existants. Éliminez les doubles saisies et garantissez la cohérence des données au sein de votre organisation."
    
    - icon: "/assets/images/undraw_product-iteration.svg"
      title: "Automatisation des flux de travail"
      description: "Transformez les tâches administratives répétitives en processus automatisés. Du suivi des factures à la gestion des demandes d’assurance, nous vous aidons à libérer un temps précieux pour que vos équipes se concentrent sur l’essentiel."
